#SERVER Port
server:
  port: '9000'

spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: ${DATABASE.URL}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update