#SERVER Port
server:
  port: '9000'

spring:
  data:
    rest:
      base-path: /resource
  batch:
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: ${DATABASE.URL}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        envers:
          boot: OFF
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF